spring:
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/book_manage_system?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yourpassword
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  # 定时任务
  task:
    scheduling:
      pool:
        size: 10

# Mybatis
mybatis:
  configuration:
    # 自动映射主键
    use-generated-keys: true
    # 驼峰命名法
    map-underscore-to-camel-case: true
    # 显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml